/*
 * const char * variable header
 * Copyright (c) 2017 Shenghua Su
 *
 * This file is generated by script, should not be modified
 */

#ifndef _MQTTKEY_H
#define _MQTTKEY_H

const char mqttKey[] =
"-----BEGIN RSA PRIVATE KEY-----\n"\
"Proc-Type: 4,ENCRYPTED\n"\
"DEK-Info: DES-EDE3-CBC,5ED538CDB9F9776D\n"\
"\n"\
"cUkKaKJ4KPqWf1/0h+xMVPhg/4sZUqE/RN2KaClS9dbabq+VGtLqGYv6rGw6/BHQ\n"\
"5YbGuIMh8LvrRhVmKoRAKg5JRNplyC40yBGLyCqer1Uxp3lHzUYw4AWkGb93x0uG\n"\
"hLn7QABwLDCDA7ce1rOGzU94DrgH7UHe1EvDZpY5lQI+J7R6B2F9XVf01t6XeOel\n"\
"fEsuHYvlkfb8XCeZ3WBXrGdlJDahFF6YEuIT0u7MzYP3IbpaMZTzz6Pl/iTaF1UX\n"\
"LTH3I14NEoV2aIymXXCGW3D6NzDmCQyk2Ey7rRSjyfiNpoUQFWMIJ64c+eYRwmjP\n"\
"GInSQnYaIC9eIav0jb+Cxulk15z1k4IN0tPV32lxHx3toP+7nCrG6CwUSK/eylyN\n"\
"Qzl3DwBnvvpIWREILahB5CKxNE5iV/7r1bmT4k0CR4bHt3yc8gtfakCG+mCHIRLp\n"\
"rPjLyMyf04aH9I95XniOYBB6YQwqon6ye6VBXI88yAYskFe0hF5rTrjX3c959D6g\n"\
"0/ZUrIljwZuEjZfZ5QXLBtgk3W/dgif4V1sSwjg6WOQYgccgLhE91b19JqRe/Ccn\n"\
"0HddFniw5++e/MRfhO5p80t/VGuH9Epd2ug+xv2cKt5s+u73l0CItqnLF+WlXRuo\n"\
"Vi1x+cRQBW1j3GJu5fh+Ivt1z6ga94rbThkv2d7TdJjYCyPZu2jr8B6lM3h1eTBO\n"\
"ollwLrkO+VYm6y0WqO2JGxhsrMHdwAjKJ7WzZ6lXaH2wqy43l8L3N7a+5SGpH/BX\n"\
"IsVzXALcHwlI0mE1870UjP/myDT4ja5U/DLtRUu0C1klap0MRvFYnBQ+Qlgw7aT5\n"\
"ZmnaiEFzDlro6yQQ0nyesGNsCzJvEAE6cIHbODh2z5Ue3+Fa9ymudNtYhMLUWn5O\n"\
"I2yX5Kq1/DpHjqjvWuIb/ShLqXzFwLMOwwcYlLDtUZGorohsWfEEFc/44tj2myGt\n"\
"giPOARMQrIOqQKEV9bnc7b6r4gNeHrNE/OGMVnwNzNNXK5ii2dO0Al+CaNDyyDO7\n"\
"iKgvfAWnj9PDYsuE4bQMr7PNLSnUR6PiJ1ki2594VSn61X/waAqGqEhvgkmt/3C7\n"\
"asSJVQkbHP3/g0xKj8e0h9rCyy64jtqujGJbxwIUuT5xxbvVy8SW0bayF5z94RPy\n"\
"N9w/CNQPYiK+TQ+WR0QspUh7Y1taT2Asr8DK7ek8Bu8nQEVSxyzo6TaY12OO6HCE\n"\
"ydlfq5mIzuptb18yPCqPR0ru5QxSnSohcpR/M93UP3CyMT1z0YSbjYDYOTZKCoFn\n"\
"wwYmKiwUFMd1NMog0cu7E4Ly5pnywwCw6dfdl5O92Y5c0Kr5UeSdCim4wh3mk7uJ\n"\
"BIyqfa+1BTpx9meIe0jVhd6g8k2FUP2g1nJlLFmWN+j4OIv9db4sUbLvkePZDteB\n"\
"amP4q6o4q3CHRwRKiZGsieoIXyttK1dcoTSdm3DFmkJYf8boEVed3OfyLrM2p/Pk\n"\
"4F7wqHlrVukN/QKH1kzUNbNAW6xr0IJeX7pnHxqDYaLx2ckwNXTYzNvKs7fjuchm\n"\
"ig4d5/qLBNB70HpgR/x/uaYd90AOMftpFbF2PnittdweDQyan6R0dou5QTQU+YIC\n"\
"-----END RSA PRIVATE KEY-----\n";

#endif // _MQTTKEY_H
