/*
 * const char * variable header
 * Copyright (c) 2017 Shenghua Su
 *
 * This file is generated by script, should not be modified
 */

#ifndef _MQTTKEY_H
#define _MQTTKEY_H

const char mqttKey[] =
"-----BEGIN RSA PRIVATE KEY-----\n"\
"Proc-Type: 4,ENCRYPTED\n"\
"DEK-Info: DES-EDE3-CBC,E3C4CC56434E7413\n"\
"\n"\
"jElPVZzZ0CD2PLjd2C9/00knXQhExDWpT+vD3409tPxAbBYT3IPhxPw7FDlOOMR3\n"\
"6JebiylPLaT1kou0UsC6o6NS+P5XoR4Fa0UOESDWOqKpcrMv/BAeYboF1EYQEZyd\n"\
"55CJg1/wZWceDyY+NA/Z0+3O6W/wONO10UFjjgPXBEzd+pNfFY2XzLkl9Lq2Ii37\n"\
"9QsUgUVy0iHKHWMvXj3/4/uiSKF3pgctjg3L1mTw64M9HXM7APFbEu1mQpREKGXP\n"\
"AlpFftJJ5JyYuukgU69a0r/Q9gN+PQRDdFTcRhLpZwXbc5M2ba/ZfKB/xWQ3xcsz\n"\
"0RoB2LhhvCn8PDGSjjCl+WNO/b8qgBOahEhYa6zX/k/4SP9XxGGYsQ+K3y6As5bV\n"\
"Du699JDA+NkwdE/oYOvUKDsPK/DAD8p4bGXYCYurUNHPy7Dh5ZDcwpTb6xuLP4Ab\n"\
"4IcplN4/5fXvbQ1FNCD2iY30yrcohR6CG4YGeIaVGsZaOJ1/2nqYr8U/dlDR/f3o\n"\
"joyNkAIWMTxdhGO6rRT+gwA7yJfujQQWghTR+iBMqbIJbfj4pvxW084cAbRIvRRV\n"\
"7fnx8dPwZTdH0udmDg+8gDbii687hTcLLtdqRnkJ8OycoUqOq+DLFtqIMP1tCFW7\n"\
"wKp0vr/UCdSJMtJacZatbeUloRS0qgm5h4sTqY7T3kV1s222Wr6wDFHPO2CUTkbt\n"\
"nSrL7lGGYM36emDk0KmgPmRVcW1eoy0WNuBo7n3mA4enmBDEdUoa9EbvrIo0Ubbc\n"\
"pkrcEktWl20wVm/zlOk3NJal/0XoD6fzHqh3g+QJBNarYZQ17Xbk5t9nZQ6NncAq\n"\
"KycglXgDZgu4+CKC4jP3tYqEubGU19CcbYmOcNYRSNd/DzTgff65zSNv1Y22TfIG\n"\
"nD0p5i9rcgkUMfYfiHgAgVS4miCXzeBHAaNc9BHdiaja2S35f+r6HmzFppdcGh4m\n"\
"U/luHbkrKRUCalT6WZb5MJAW8Uo/dxdH9t59RSsKUiO8p61pBdRjdwcOMfus9t8m\n"\
"8lEFPdMyghwuFA/bGca3JQuV0I3PemU5m9JXThYWex2DqFlONLw4erdacUxK9gL5\n"\
"NnUIf8zCztAxf1ja+x31JUp2KIoMXD/A3nsioH4KGiGs2+XsgHkXZHcbpfDmMi0P\n"\
"IvER7SKPn1TYfCBCeHVJuz2UB4G17NK1+YEPHtsNelfLZ2t3SYkTFK6MzmyOKdJ5\n"\
"frdW9jgCPb2HtYqVsa9bs9ogGYQ3d0udAdAtAJya0gP/P5tSvZF9Ti4TA2HPXIyK\n"\
"cd2Ai1MVf3CASm67t4yRQi9l7xj6ZRRz1EyclvKq1s2YjmWa4uXvxHFZ7Lb64oiJ\n"\
"rhcvV40qmmb/ZJZyw3O9C1hr0P5IjoWH6USemdZ9WH+nXGmyqF8pNn1bazULC5No\n"\
"ZcUuqrRTxsQLq5VMcGhQ/VxpM8NChtMt3/jbBcyoKtL+PX8t5/cvNffMUCGgD8uU\n"\
"csRuVksOVfxtWMYjPN13SLLs3vWqbC5aIlnx68yLzU1L1kEMLaBmEWInqZmDbcwf\n"\
"ARHnsVc/xgjSnX3oU1PHnD6+qVk4L9TVjnteMVGPsw5a28ePZL0P8tydiQewsjcP\n"\
"-----END RSA PRIVATE KEY-----\n";

#endif // _MQTTKEY_H
