/*
 * const char * variable header
 * Copyright (c) 2018 Shenghua Su
 *
 * This file is generated by script, should not be modified
 */

#ifndef _MQTTCRT_H
#define _MQTTCRT_H

const char mqttCrt[] =
"gpRjf4wAQHy/ntoJQih99Q8NDE+DZkLNQZnjbr6W2m8=\n"\
"au3owZzk81I+BcaeaJ28I714i4qlKI0gRfSfTmjG9uv4b/uoPELMK/Wb8SYgW7SrXRic2+GRsnv3VmrtkIcPgjAmqC2Z095fsLQtpeZugA4=\n"\
"v9h9wNZTMbs/PvtQwaUPI//5Lrn2UvHepSc2unumONgQutdNgT/XFgYN7VAvbFHWTJDZL56akx3WMoVI7kfYbpiHL6q/6QfZlheMYMY/f60=\n"\
"C7jbKxrr+WUUmZi4ch3inqw+PI9rQA466ep0faLLcp6WJM3Ef3XkNqaeATo3LynUKksUb6Dl68fDa5gv3r0eiv5OKZtEv88jzteoTtdHvdk=\n"\
"xbUYLk6Kpm/2p1bi6Oy1wyqcnZhW68v2Ai0i/tCHy8D3Bjz0Qm3ey9BOloMmvYLcWsrZ3EJ81woNT7yOpwAXtCEZXR483r5VyO5byARf5FA=\n"\
"JjmQhjiY0aPQ0GmJjjLw1OAsTrSQ3eWx5Dteijr2kO2BzTcsj9uDA3wh17avISxMsNndl6lG6KyqTuAnmz9HIOVK/JWjJgjOzto0YG3I5Bs=\n"\
"m1Jv+WCTgh5Ly4BF8dlSUkXce3QA5YkkK8jcV8LFXgp+8WlTt3MJ5i3zK4/CnlsNXMUR9My/t+4Gfc04mMfK1YRJGMjfjrq091j46pm+/J4=\n"\
"/XhRYCUzT17SKvXvwj+OX0AUDOQ1chOZfR97LMNr1/sH4sglLA4HBdcLJYjjqcB8qDK1bZiApMBpo5sa2UEf35dOtIkhiKVucw5uFu6jwx4=\n"\
"M+bzTUhRFM9cVfrVaY4B/6jzz0uKS51XSrcj+S/XP/fMYIX8sKYNCE/F8o1gkFRObliHyRmZpuNwV6oDkpwLFonwUaDtp3QfQ4lTtSGSJCg=\n"\
"Ge6kV8dl7X63XwUVoFscBEqaNyEJ5RboAviSscq/xuC8SpGBY+Je+pYrtvc/Qrt9I9SMCKmiow4cMVSCH0jAZcBmfoXj6ChOW29Z5bTMW14=\n"\
"uJmysD+I7p1hmV2EgVQucsfB0s2u+LikA1u3Ig5DpRX3rXBiK6lRziHq9wCxlNwc4KcP7B7iTKr23TwFfhooFBO3tAsT46CqR4tCRuyXezQ=\n"\
"KCzJtnICzA+zi1IqfU0kzJAw2wgbRnNd8rMlXMP39L4tRJZe2W0vSbv/fPtYxuzcb/ri09nECflAvF12HJK9Rrzx1TiOGz8aUn6fN3IZA68=\n"\
"b2gW6tEf/3JsNcCI30i/5S8VqQOKbuBMZUL2WkiLHc2Ndc/zPQa5OMSei/xEp0aI4B0iAZ1ksLbX7au7OZQleWP3SdqNh7pvLAina3z0X88=\n"\
"9r02Gs5/LiddSmNVBMiFSshzV9EWDh9XYIYbBrUlywYimOWs/lRsdDKUtrVPJFuShyNPlTmSQqEnDQLiOa1fRB2rpCqmzBN9+dV4ABWQFlY=\n"\
"CyzJvzxEKOJMuaWjWdbsKixYGUxzFeTIyKdUs1eygyugu+6q7xbEJFC0ry229sHq+lFtZ8N5q5lUlKS7VXa5rpmYb1t8lkw+sspa2KealV0=\n"\
"ZSKvKrSFZ8qtNQg99SL4F/iBC6Oz3o7sQdnKPVQu5XMeVeEsy0KtCfvC460H+fNFX4xLXA3NNuBzGU7Ak2/lW4zcTo8a01PjiGNN85gng0A=\n"\
"uthYBTT0RhZ4MZdBL01kww8Pxi+QLujgzvGVgTO0Qp02SX61JZSZUfuLJ5qTj2nrI7GbijnyQUwR4waNJGSaiJevaJd8WYAMjmxyEC+T63s=\n"\
"oJLFQObZpWKM3wL54snPslDpk7le9PmdLVIvDIuwFkXNDHB9Ddzr5yJ97t+WF1qMGVruWcY/7rpuumr4neKGvqqsJnNh/w8Pl4nqlk9YWC4=\n"\
"uA+Ui/5veghR8Rg8euMH+q30HYU19AANmq7CAB0jy03plIdImFebcr2oHMABjhAAoZWQVu5oF7Pdf/q1Gw3LZajPD1VUJJJM9MTc+Lhrqig=\n"\
"GgtLCPFnB2DR5UpBo2DixoOgFIkOjrCmtD65yfmqAq22La/HKPuQL7c9vm4O/Uv4V5iugOnqeltIRawEK+BAC5haOD+0f3dS5O7fu4RYVFg=\n"\
"bRaGWVf59Nfsl337Ydx/uzxDxw2vV8W36AmANenyPnI=\n"\
"TS7zn9Cf/DfW/g0lDFycRkbSZPgUZxiVX9c576166GM=\n";

#endif // _MQTTCRT_H
