/*
 * const char * variable header
 * Copyright (c) 2018 Shenghua Su
 *
 * This file is generated by script, should not be modified
 */

#ifndef _MQTTKEY_H
#define _MQTTKEY_H

const char mqttKey[] =
"-----BEGIN PRIVATE KEY-----\n"\
"MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCyGcJF4jQ7H4Pw\n"\
"jR7qUCcU0k+MpWbbz+TpyBzYso3ZGhXLxmYJvNd4J8RAMlOu/uPsIQgBm/psOx6/\n"\
"YFv0BTXTskcslM+sppMerNIjZyyXuUJfW3jBkpdO7Q1l/Ua2PCiTvEfLvdpZcoSq\n"\
"09Fuyw2dcck6iEHt1lTa8ABLDcYc+WJj3D5ZLB/wlqi/bpiDPxfmIygRmhhp20Ib\n"\
"DNqj9Oy2pxhr8Brq2mmZE8EXtBEDP5OKUf/tIBITh17nFaCs9kHjttTSbvlLEike\n"\
"YG1fbaBxFJo5G0RK+a1yQt/BO4jt0IpTMnzKJ/ASgYEsnDOty9pUBQKUTjfIwO0a\n"\
"y7P5PMvTAgMBAAECggEADjtat+TkkZjqHS3Zu5WeGd7Ydn+9IXGSdFAGZhaWmTOp\n"\
"bDg1bS/G9BYRa6PZ5hD+O59EGYTSVRXAVkCn+G72Jy2G3HwjwEMrXHco76VN/e3S\n"\
"7PXNR4KkTq1Itc6weN2DzJJuFkzchutMyK3WfYkCVIOENgYvZocLDtfA3j6Ch0wQ\n"\
"Ooz7zxAvVtlT9GJ4skm7rxuh27oV0cqMsGIzD5PmGGElpxKu7q0s5axzd9K5916x\n"\
"/xPRQg+RsTURw4ntuanBTNte1FI2dXOLcQydljcRLZm7prwaYuzggArnJd1RZu9y\n"\
"iFuj9OP7n3LRZ2SqnUMn7ogDA5KRINysq1MOeUnMoQKBgQDbGZF/mUoKxWlRHPZy\n"\
"CkECr+xGO4YKbicwdyH5PwhCfKtvRXGnx1HJ7JoV29r3Z+v1HvA3pzJZwsQK2MYY\n"\
"cBh++uagobC8s1bKRkMpSkRqk0hI/zrKFeHA3Wo47421RsgcHwXv8m6OJHkAl06S\n"\
"GeuI4+oLETXlnjTTBO+uRqFfowKBgQDQGITM7F3usjVFXdEdAEeOJ+zTfvjAUHLJ\n"\
"ZQK2rnJHLRDsWomxTOImNP0CrAZgPOa9FIasK+HnAnbT8+3NYNIUg5fCZ+4OEpMY\n"\
"nocEfoVJYw6wIkdFtKpCRvTAAVEuOF6KE5wJa1qGRxOOmjAnhTj7d9TkE7YUswnB\n"\
"BU0yNpPmEQKBgCl36WXxKWZofspvZOWosy1DBsE0OuZ2esxdf/ygxXtwBTKGPkC3\n"\
"JO/G7FL+za7N6Ib4WBbwekMq7dfvt26gqMI/0q7Ma5sLhn26VrPV7qUNQz0tsX7W\n"\
"LWhHf/dOv89zmiRYatNDW1Fj7dMC0Egux7mdCYsWstDG5NCbupGNpLVpAoGATR7J\n"\
"GKkAptWkqHB8byMLYcOqITeNOLiX0ct9lfZQo9Av1Wg4X1z+8unwWm0mb8QiPzC8\n"\
"OFKLBfID18ku+E5JjRC3zXR25QA9Q4J8x02cV/Y+G0iY4VxzPNzPF9llHJwHbWSX\n"\
"D2aZxenRdafu8LaOx6NBYsVrVYCEvOQaF+HiLgECgYEAwfwBSP/BOCNRydryDX+u\n"\
"3QnFP1P5LCzHGslO0+lAvc+2th/Oivi88+hUyKcXWMJry35Rt3LHA/nRQS3YSDUo\n"\
"fztlWJjeIE4MoWHPgTWHiEYt5BzFvVYQMkccDC1I9XRfk84EZyCq/FFZ2mpXC2i0\n"\
"XiCknvaJdtg/KFQq2VXqmJk=\n"\
"-----END PRIVATE KEY-----\n";

#endif // _MQTTKEY_H
