/*
 * const char * variable header
 * Copyright (c) 2018 Shenghua Su
 *
 * This file is generated by script, should not be modified
 */

#ifndef _MQTTUSER_H
#define _MQTTUSER_H

const char mqttUser[] =
"QM5pHTtO2M1Pz8naZUK+/A==";

#endif // _MQTTUSER_H
