/*
 * const char * variable header
 * Copyright (c) 2018 Shenghua Su
 *
 * This file is generated by script, should not be modified
 */

#ifndef _SKI_H
#define _SKI_H

const char ski[] =
"azRwUi8rMGdFaE9IWHVjMjJuK3Zic3BPQXNxOEVD";

#endif // _SKI_H
