#
# Main Makefile. This is basically the same as a component makefile.
#
# (Uses default behaviour of compiling all source files in directory, adding 'include' to include path.)


# COMPONENT_PRIV_INCLUDEDIRS=
# COMPONENT_ADD_LDFLAGS=
# COMPONENT_DEPENDS=
# COMPONENT_ADD_LINKER_DEPS=
# COMPONENT_SUBMODULES=

COMPONENT_ADD_INCLUDEDIRS := . Common ST7789V
# COMPONENT_PRIV_INCLUDEDIRS := ../Spi
# COMPONENT_EXTRA_INCLUDES=
COMPONENT_SRCDIRS := Common ST7789V
# COMPONENT_OBJS=
# COMPONENT_EXTRA_CLEAN=
# COMPONENT_OWNBUILDTARGET=

# CFLAGS=
# CPPFLAGS=
# CXXFLAGS=
