/*
 * CmdSetUtility utility methods
 * Copyright (c) 2016 Shenghua Su
 *
 * build:  g++ -o f2sh file2StrHeader.cpp
 * export: ./f2sh -i inputfile -o outputfile
 *
 */

#include <iostream>
#include <fstream>
#include <string>
#include <algorithm>

using namespace std;

int main( int argc, const char* argv[])
{
	bool formatErr = false;

	do { // flow control

		if (argc != 7) {
			formatErr = true;
			break;
		}

		int flagCount = (argc - 1) / 2;
		int inputFileNameArgIndex = -1;
		int outputFileNameArgIndex = -1;
		int stringNameArgIndex = -1;

		for (int i = 0; i < flagCount; ++i) {

			const char *flag = argv[1 + i * 2];
			int fileNameArgIndex = 2 + i * 2;

			if (string(flag) == "-i")
				inputFileNameArgIndex = fileNameArgIndex;
			else if (string(flag) == "-o")
				outputFileNameArgIndex = fileNameArgIndex;
			else if (string(flag) == "-n")
				stringNameArgIndex = fileNameArgIndex;
			else {
				formatErr = true;
				break;
			}
		}
		if (formatErr) break;

		if (inputFileNameArgIndex == -1 || outputFileNameArgIndex == -1 || stringNameArgIndex == -1) {
			formatErr = true;
			break;
		}

		// file stream
		std::fstream fi(argv[inputFileNameArgIndex], std::fstream::in);
		std::fstream fo(argv[outputFileNameArgIndex], std::fstream::out);
		std::string linestr;
		std::string upercaseName(argv[stringNameArgIndex]);
		std::transform(upercaseName.begin(), upercaseName.end(), upercaseName.begin(), ::toupper);
		// write string name
		fo <<  "/*\n" \
			   " * const char * variable header\n" \
			   " * Copyright (c) 2017 Shenghua Su\n" \
			   " *\n" \
			   " * This file is generated by script, should not be modified\n" \
			   " */\n\n";
		fo << "#ifndef _" << upercaseName << "_H" << std::endl;
		fo << "#define _" << upercaseName << "_H" << std::endl << std::endl;

		fo << "const char " << argv[stringNameArgIndex] << "[] =" << std::endl;
		// read source and write target
		while (!fi.eof()) {
			std::getline(fi, linestr);
			if (linestr.length() > 0) {
				fo << "\"";
				fo << linestr;
				fo << "\\n\"";
			}
			else {
				fo << "\"";
				fo << "\\n\"";
			}
			if (fi.peek() != EOF) {
				fo << "\\\n";
			}
		}
		fo << ";" << std::endl << std::endl;
		fo << "#endif // _" << upercaseName << "_H" << std::endl;

		// close stream
		fi.close();
		fo.close();

	} while (false); // end of flow control

	if (formatErr) {
		std::cout << "use format: " << argv[0] << " -i inputFile -n stringName -o outputFile" << std::endl;
		return -1;
	}
	else
		return 0;
}
