/*
 * const char * variable header
 * Copyright (c) 2018 Shenghua Su
 *
 * This file is generated by script, should not be modified
 */

#ifndef _MQTTPASSWD_H
#define _MQTTPASSWD_H

const char mqttPasswd[] =
"P71licaFY7nbdEpYaj5bMgZzuDuv/T7U2qkshFGDZL0=";

#endif // _MQTTPASSWD_H
